---
version: "3"
services:
  hydra2:
    build:
      context: .
    container_name: hydra2
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - config:/config
    ports:
      - 5076:5076
    restart: unless-stopped
volumes:
  config:
